### ISSUE TITLE
Upgrade to 30.0.0

### ISSUE THREAD

**Issue by jreyeshdez** [arm64-compat/apache-druid#12]
Please @anuragagarwal561994 if you can upgrade to lates. It still unsure how I proceed to do it myself. You mentioned I just need to go to sub-module and update tag and push however I think it might be best you add more detailed instructions (screenshots or short video). When cloning this repo the module `druid` has nothing so not sure what tag I should update.

**Comment by jreyeshdez** [comment]
Managed to push PR https://github.com/arm64-compat/apache-druid/pull/13

**Comment by altaiezior** [comment]
This is released, thanks for contribution.
